'use strict';
module.exports = {
  USERS_COLLECTION: 'users',
  PRODUCTS_COLLECTION: 'products',
  ORDER_EVENTS_COLLECTION: 'orderEvents',
  ORDER_ITEMS_COLLECTION: 'orderEvents',
  ORDERS_COLLECTION: 'orders',
  PRODUCT_CATEGORIES_COLLECTION: 'productCategories',
  EVENT_ACTION_ADD_PRODUCT: 'ADD_PRODUCT',
  EVENT_ACTION_PAYMENT: 'PAYMENT',
  ORDER_STATUS_IN_PROGRESS: 'IN_PROGRESS',
  ORDER_STATUS_PAID: 'PAID',
  ORDER_STATUS_PARTIALLY_PAID: 'PARTIALLY_PAID',
  ORDER_STATUS_READY: 'READY',
  ORDER_STATUS_DELIVERED: 'DELIVERED',
};
